In [6]:
import numpy as np


In [6]:
# From list
a = np.array([1, 2, 3])

# Multi-dimensional
b = np.array([[1,2,3],[4,5,6]])

# Special arrays
np.zeros((2,3))       # 2x3 matrix of 0s
np.ones((3,3))        # 3x3 matrix of 1s
np.full((2,2), 7)     # 2x2 matrix filled with 7
np.eye(3)             # 3x3 Identity matrix
np.arange(0,10,2)     # [0 2 4 6 8]
np.linspace(0,1,5)    # [0. 0.25 0.5 0.75 1.]


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
arr.shape     # (2,3) → rows x cols
arr.ndim      # 2 → dimensions
arr.size      # 6 → total elements
arr.dtype     # data type (e.g., int32, float64)


dtype('int32')

In [10]:
a = np.array([10,20,30,40,50])
a[0]      # 10
a[-1]     # 50
a[1:4]    # [20 30 40]

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b[0,2]    # 3 (row0,col2)
b[:,1]    # [2 5 8] (all rows, col1)
b[1,:]    # [4 5 6] (row1, all cols)


array([4, 5, 6])

In [12]:
x = np.array([1,2,3])
y = np.array([4,5,6])

x + y     # [5 7 9]
x - y     # [-3 -3 -3]
x * y     # [ 4 10 18]
x / y     # [0.25 0.4 0.5]
x ** 2    # [1 4 9]

np.sqrt(x)     # [1. 1.41 1.73]
np.mean(y)     # 5.0
np.sum(y)      # 15
np.max(y)      # 6
np.min(y)      # 4


4

In [14]:
a = np.arange(6)       # [0 1 2 3 4 5]
a.reshape(2,3)         # [[0 1 2],[3 4 5]]
a.reshape(3,2)         # [[0 1],[2 3],[4 5]]

b = np.array([[1,2],[3,4]])
b.T                    # [[1 3],[2 4]] (transpose)


array([[1, 3],
       [2, 4]])

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate([a,b])     # [1 2 3 4 5 6]
np.vstack([a,b])          # [[1 2 3],[4 5 6]]
np.hstack([a,b])          # [1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

In [18]:
np.random.rand(2,2)      # Random floats (0–1)
np.random.randn(2,2)     # Random normal dist
np.random.randint(1,10,5) # 5 random ints [1–9]


array([6, 4, 6, 5, 6])

In [8]:
a=np.array([1,2,3,4,5,6,7,8])
b = a.reshape((2,4)) 
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
c=a.reshape((2,2,2))
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.arange(0,5,1)


array([0, 1, 2, 3, 4])

In [42]:
np.linspace(0,10,5) 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [56]:
arr=np.full((2,3),7)
print(arr)

[[7 7 7]
 [7 7 7]]


In [58]:
arr.shape

(2, 3)

In [60]:
arr.size


6

In [62]:
arr.ndim

2

In [66]:
arr.dtype

dtype('int32')

In [68]:
a[0]

1

In [70]:
a[3]

4

In [84]:
#10
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [86]:
a[2:2]

array([], dtype=int32)

In [88]:
a[5]

6

In [90]:
a[1:4]

array([2, 3, 4])

In [92]:
a[-1]

12

In [94]:
a[1:2]

array([2])

In [108]:
b = np.array([[1,2,3],
              [4,5,6]
              ,[7,8,9]])

In [102]:

b[0,2]    # 3 (row0,col2)


3

In [112]:
b[:,2]    # [2 5 8] (all rows, col1)

array([3, 6, 9])

In [114]:
b[0,:]    # [4 5 6] (row1, all cols)

array([1, 2, 3])

In [116]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,8])

In [120]:
x+y # add

array([ 7,  9, 11, 13, 13])

In [122]:
x-y # sub

array([-5, -5, -5, -5, -3])

In [124]:
x*y # mul

array([ 6, 14, 24, 36, 40])

In [126]:
x/y # div

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.625     ])

In [128]:
np.max(y)

9

In [130]:
np.min(y)

6

In [134]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [136]:
np.mean(y)

7.6

In [142]:
np.median(x)

3.0

In [146]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [156]:
a=np.arange(6)
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [158]:
a=np.arange(12)
a.reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [160]:
np.concatenate([x,y])      

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 8])

In [166]:
np.hstack([x,y]) 

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 8])

In [170]:
np.vstack([x,y])          

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 8]])

In [178]:
np.random.rand(3,2)      # Random floats 


array([[0.56051201, 0.58651785],
       [0.30253643, 0.68412258],
       [0.5734582 , 0.08265937]])

In [180]:

np.random.randn(2,3)     # Random normal dist

array([[-0.11039388,  0.64240741,  0.58828948],
       [-0.69264814,  1.23679967,  0.14702318]])

In [182]:
np.random.randint(1,10,2)

array([3, 9])

In [184]:
a[4]

4